// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/booking': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/booking.post').default>>>>
    }
    '/api/shopify/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shopify/products.get').default>>>>
    }
    '/api/shopify/storefront-test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shopify/storefront-test.get').default>>>>
    }
    '/api/shopify/test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shopify/test.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}